let

  // Data Source
  Source = #table(
    {
      "Region", 
      "Region_key", 
      "Region_short",
      "Region_url"
    }, 
    {
      {
        "Central Bohemian Region", 
        0, 
        "Central Bohemia",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Central_Bohemian_Region_CoA_CZ.svg/100px-Central_Bohemian_Region_CoA_CZ.svg.png"

      }, 
      {
        "Hradec Králové Region", 
        1, 
        "Hradec Králové",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Hradec_Kralove_Region_CoA_CZ.svg/100px-Hradec_Kralove_Region_CoA_CZ.svg.png"

      }, 
      {
        "Karlovy Vary Region", 
        2, 
        "Karlovy Vary",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Karlovy_Vary_Region_CoA_CZ.svg/99px-Karlovy_Vary_Region_CoA_CZ.svg.png"

      }, 
      {
        "Liberec Region",
        3,
        "Liberec",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Liberec_Region_CoA_CZ.svg/100px-Liberec_Region_CoA_CZ.svg.png"
      }, 
      {
        "Moravian-Silesian Region", 
        4, 
        "Moravia-Silesia",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Moravian-Silesian_Region_CoA_CZ.svg/120px-Moravian-Silesian_Region_CoA_CZ.svg.png"

      }, 
      {
        "Olomouc Region",
        5,
        "Olomouc",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Olomouc_Region_CoA_CZ.svg/120px-Olomouc_Region_CoA_CZ.svg.png"
      }, 
      {
        "Pardubice Region", 
        6, 
        "Pardubice",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Pardubice_Region_CoA_CZ.svg/120px-Pardubice_Region_CoA_CZ.svg.png"

      }, 
      {"Plzeň Region",
        7,
        "Plzeň",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Plzen_Region_CoA_CZ.svg/120px-Plzen_Region_CoA_CZ.svg.png"
      }, 
      {
        "Prague",
        8,
        "Prague",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Coat_of_arms_of_Prague.svg/120px-Coat_of_arms_of_Prague.svg.png"
      }, 
      {
        "South Bohemian Region", 
        9, 
        "South Bohemia",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/South_Bohemian_Region_CoA_CZ.svg/120px-South_Bohemian_Region_CoA_CZ.svg.png"

      }, 
      {
        "South Moravian Region", 
        10, 
        "South Moravia",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/South_Moravian_Region_CoA_CZ.svg/99px-South_Moravian_Region_CoA_CZ.svg.png"

      }, 
      {
        "Ústí nad Labem Region", 
        13, 
        "Ústí nad Labem",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Usti_nad_Labem_Region_CoA_CZ.svg/120px-Usti_nad_Labem_Region_CoA_CZ.svg.png"

      }, 
      {
        "Vysočina Region", 
        11, 
        "Vysočina",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/CZE_Kraj_Wysoczyzna_COA.svg/120px-CZE_Kraj_Wysoczyzna_COA.svg.png"

      }, 
      {
        "Zlín Region",
        12,
        "Zlín",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Zlin_Region_CoA_CZ.svg/100px-Zlin_Region_CoA_CZ.svg.png"
      }
    }
  )

// Result
in

  // Data Source
  Source