let

  // Data Source
  Source = #table(
    {
      "Region", 
      "Region_key", 
      "Region_short",
      "Region_url"
    }, 
    {
      {
        "Central Bohemian Region", 
        0, 
        "Central Bohemia",
        "https://raw.githubusercontent.com/Thepilli/political_ads/refs/heads/main/PBI/assets/region_logos/region_logo_0.png"

      }, 
      {
        "Hradec Králové Region", 
        1, 
        "Hradec Králové",
        "https://raw.githubusercontent.com/Thepilli/political_ads/refs/heads/main/PBI/assets/region_logos/region_logo_1.png"

      }, 
      {
        "Karlovy Vary Region", 
        2, 
        "Karlovy Vary",
        "https://raw.githubusercontent.com/Thepilli/political_ads/refs/heads/main/PBI/assets/region_logos/region_logo_2.png"

      }, 
      {
        "Liberec Region",
        3,
        "Liberec",
      "https://raw.githubusercontent.com/Thepilli/political_ads/refs/heads/main/PBI/assets/region_logos/region_logo_3.png"
      }, 
      {
        "Moravian-Silesian Region", 
        4, 
        "Moravia-Silesia",
        "https://raw.githubusercontent.com/Thepilli/political_ads/refs/heads/main/PBI/assets/region_logos/region_logo_4.png"

      }, 
      {
        "Olomouc Region",
        5,
        "Olomouc",
        "https://raw.githubusercontent.com/Thepilli/political_ads/refs/heads/main/PBI/assets/region_logos/region_logo_5.png"
      }, 
      {
        "Pardubice Region", 
        6, 
        "Pardubice",
        "https://raw.githubusercontent.com/Thepilli/political_ads/refs/heads/main/PBI/assets/region_logos/region_logo_6.png"

      }, 
      {"Plzeň Region",
        7,
        "Plzeň",
        "https://raw.githubusercontent.com/Thepilli/political_ads/refs/heads/main/PBI/assets/region_logos/region_logo_7.png"
      }, 
      {
        "Prague",
        8,
        "Prague",
        "https://raw.githubusercontent.com/Thepilli/political_ads/refs/heads/main/PBI/assets/region_logos/region_logo_8.png"
      }, 
      {
        "South Bohemian Region", 
        9, 
        "South Bohemia",
        "https://raw.githubusercontent.com/Thepilli/political_ads/refs/heads/main/PBI/assets/region_logos/region_logo_9.png"

      }, 
      {
        "South Moravian Region", 
        10, 
        "South Moravia",
        "https://raw.githubusercontent.com/Thepilli/political_ads/refs/heads/main/PBI/assets/region_logos/region_logo_10.png"

      }, 
      {
        "Ústí nad Labem Region", 
        13, 
        "Ústí nad Labem",
        "https://raw.githubusercontent.com/Thepilli/political_ads/refs/heads/main/PBI/assets/region_logos/region_logo_13.png"

      }, 
      {
        "Vysočina Region", 
        11, 
        "Vysočina",
        "https://raw.githubusercontent.com/Thepilli/political_ads/refs/heads/main/PBI/assets/region_logos/region_logo_11.png"

      }, 
      {
        "Zlín Region",
        12,
        "Zlín",
        "https://raw.githubusercontent.com/Thepilli/political_ads/refs/heads/main/PBI/assets/region_logos/region_logo_12.png"
      }
    }
  )

// Result
in

  // Data Source
  Source