table Calculations
	lineageTag: 3e7d34b1-bb8c-4188-95f7-b7204c4d8a1e

	/// This measure is the sum of column 'F_Demographic_Distribution'[Audience_dem]
	measure 'SUM of Audience_dem' = SUM( F_Demographic_Distribution[Audience_dem] )
		formatString: #,##0.00
		displayFolder: Aggregations
		lineageTag: 0badc62e-735f-4f69-889d-f3fa8a7010d4

	/// This measure is the sum of column 'F_Demographic_Distribution'[Impressions_dem]
	measure 'SUM of Impressions_dem' = SUM( F_Demographic_Distribution[Impressions_dem] )
		formatString: #,##0.00
		displayFolder: Aggregations
		lineageTag: 0434b027-ddfa-48aa-9524-7c299eb14d05

	/// This measure is the sum of column 'F_Demographic_Distribution'[Spendings_dem]
	measure 'SUM of Spendings_dem' = SUM( F_Demographic_Distribution[Spendings_dem] )
		formatString: #,##0.00
		displayFolder: Aggregations
		lineageTag: fea38ddf-bfcb-4ab3-b31e-334c3243ba9b

	/// This measure is the sum of column 'F_Regional_Distribution'[Audience_reg]
	measure '_SUM of Audience_reg' = SUM( F_Regional_Distribution[Audience_reg] )
		formatString: #,##0.00
		displayFolder: Aggregations
		lineageTag: 184fea54-f894-4990-bd65-c00bbbf7a4d9

	/// This measure is the sum of column 'F_Regional_Distribution'[Impressions_reg]
	measure '_SUM of Impressions_reg' = SUM( F_Regional_Distribution[Impressions_reg] )
		formatString: #,##0.00
		displayFolder: Aggregations
		lineageTag: 3fa9e725-b74c-409c-bf7a-b7ff3e33f559

	/// This measure is the sum of column 'F_Regional_Distribution'[Spendings_reg]
	measure '_SUM of Spendings_reg' = SUM( F_Regional_Distribution[Spendings_reg] )
		formatString: #,##0.00
		displayFolder: Aggregations
		lineageTag: 1c18ac8f-6adc-401d-b0ef-fb650b3fa887

	/// This measure is the DISTINCTCOUNT of column 'F_Ad_delivery'[Beneficiary_key]
	measure 'DISTINCTCOUNT of Beneficiary_key' = DISTINCTCOUNT( F_Ad_delivery[Beneficiary_key] )
		formatString: 0.00
		displayFolder: Aggregations
		lineageTag: bb88b62b-0b1f-45be-8aeb-d88375bb533e

	/// This measure is the DISTINCTCOUNT of column 'F_Ad_delivery'[Bylines_key]
	measure 'DISTINCTCOUNT of Bylines_key' = DISTINCTCOUNT( F_Ad_delivery[Bylines_key] )
		formatString: 0.00
		displayFolder: Aggregations
		lineageTag: 283ef8ac-e666-4a2d-ad74-c2144731f6b2

	/// This measure is the DISTINCTCOUNT of column 'F_Ad_delivery'[Payer_key]
	measure 'DISTINCTCOUNT of Payer_key' = DISTINCTCOUNT( F_Ad_delivery[Payer_key] )
		formatString: 0.00
		displayFolder: Aggregations
		lineageTag: 08fb1552-7d42-4c04-9076-826bfb19d328

	/// This measure is the DISTINCTCOUNT of column 'F_Ad_delivery'[_id]
	measure 'DISTINCTCOUNT of _id' = DISTINCTCOUNT( F_Ad_delivery[_id] )
		formatString: 0.00
		displayFolder: Aggregations
		lineageTag: 63e40180-2664-4afe-aa41-d59b860d3e23

	/// This measure is the DISTINCTCOUNT of column 'F_Ad_delivery'[page_id]
	measure 'DISTINCTCOUNT of page_id' = DISTINCTCOUNT( F_Ad_delivery[page_id] )
		formatString: 0.00
		displayFolder: Aggregations
		lineageTag: d040afd2-66d6-46c7-aaa2-781dc5c5be95

	/// This measure is the sum of column 'F_Reach_Distribution'[Reach]
	measure 'SUM of Reach' = SUM( F_Reach_Distribution[Reach] )
		formatString: #,##0.00
		displayFolder: Aggregations
		lineageTag: 1c888349-738d-4311-8a8a-25d41612061c

	/// This measure is the sum of column 'F_Ad_delivery'[eu_total_reach]
	measure 'SUM of eu_total_reach' = SUM( F_Ad_delivery[eu_total_reach] )
		formatString: #,##0.00
		displayFolder: Aggregations
		lineageTag: 123591a2-89da-474a-af7c-e3fe9b7184d6

	/// This measure is the sum of column 'F_Ad_delivery'[days_running]
	measure 'SUM of days_running' = SUM( F_Ad_delivery[days_running] )
		formatString: #,##0.00
		displayFolder: Aggregations
		lineageTag: 260a467e-5a48-417b-83b2-74d6a4eb3a9e

	measure 'Running ads' =
			VAR MinDate = MIN( D_Calendar[Date] )
			VAR MaxDate = MAX( D_Calendar[Date] )
			VAR Result =
			    CALCULATE
			    (
			        COUNTROWS( F_Ad_delivery ),
			        F_Ad_delivery[ad_delivery_start_time] <= MaxDate,
			        F_Ad_delivery[ad_delivery_stop_time] > MinDate,
			        REMOVEFILTERS( D_Calendar )
			    )
			RETURN
			    Result
		formatString: #,##0
		displayFolder: KPI
		lineageTag: 065ca903-6c6e-4d72-9b3b-c40ffe8f1236

	measure 'Running ads AVG' = AVERAGEX( D_Calendar, [Running ads] )
		formatString: #,##0.00
		lineageTag: 5560503d-1c90-44e4-bd5f-15276a3ce50d

	measure 'Running ads EOP' = CALCULATE( [Running ads], LASTDATE( D_Calendar[Date] ) )
		formatString: #,##0
		lineageTag: 1bfac479-917f-40cf-ab4c-360c93445fa4

	measure 'Started ads' =
			VAR MinDate = MIN( D_Calendar[Date] ) -- Start of the selected period
			VAR MaxDate = MAX( D_Calendar[Date] ) -- End of the selected period
			RETURN
			    CALCULATE
			    (
			        COUNTROWS( F_Ad_delivery ), -- Count ads that overlap the period
			        F_Ad_delivery[ad_delivery_start_time] <= MaxDate, -- Ad starts on or before the end of the period
			        F_Ad_delivery[ad_delivery_stop_time] >= MinDate -- Ad ends on or after the start of the period
			
			    )
		formatString: #,##0
		displayFolder: KPI
		lineageTag: 715c156c-d792-40d5-bbbe-9be772451563

	measure 'Stopped ads' =
			VAR MinDate = MIN( D_Calendar[Date] ) -- Start of the selected period
			VAR MaxDate = MAX( D_Calendar[Date] ) -- End of the selected period
			RETURN
			    CALCULATE
			    (
			        COUNTROWS( F_Ad_delivery ), -- Count ads that overlap the period
			        F_Ad_delivery[ad_delivery_start_time] <= MaxDate, -- Ad starts on or before the end of the period
			        F_Ad_delivery[ad_delivery_stop_time] >= MinDate -- Ad ends on or after the start of the period
			        ,
			        USERELATIONSHIP( D_Calendar[Date], F_Ad_delivery[ad_delivery_stop_time] )
			    )
		formatString: #,##0
		displayFolder: KPI
		lineageTag: 75b7d26f-fff0-4faa-a281-726092c88b86

	measure Audience = [SUM of Audience_dem]
		formatString: #,##0
		displayFolder: KPI
		lineageTag: 6f310049-1570-45f1-a308-39c71e4f0b26

	measure Impressions = [SUM of Impressions_dem]
		formatString: #,##0
		displayFolder: KPI
		lineageTag: 98e8fca1-2fce-485b-9f53-f4237ea6182a

	measure Spendings = [SUM of Spendings_dem]
		formatString: #,##0
		displayFolder: KPI
		lineageTag: 09c8c94e-70f4-47af-8ce6-7b837ed6ee45

	measure Reach = [SUM of Reach]
		formatString: #,##0
		displayFolder: KPI
		lineageTag: 76accc22-1e53-4f44-a867-d213b5f98923

	measure 'Audience per day' = DIVIDE( [SUM of Audience_dem], [Running days] )
		formatString: #,##0
		displayFolder: KPI
		lineageTag: bac9f1f1-a904-4009-8b97-73a1f2ce592f

	measure 'Impressions per day' = DIVIDE( [SUM of Impressions_dem], [Running days] )
		formatString: #,##0
		displayFolder: KPI
		lineageTag: 8b738354-78ec-466d-91fb-d5f84a4c2f12

	measure 'Reach per day' = DIVIDE( [SUM of Reach], [Running days] )
		formatString: #,##0
		displayFolder: KPI
		lineageTag: aa0ef939-fb94-4280-9f09-a1eebde05c1d

	measure 'Spendings per day' = DIVIDE( [SUM of Spendings_dem], [Running days] )
		formatString: #,##0
		displayFolder: KPI
		lineageTag: bcf81c00-45bb-4ecd-b7dc-2d903aa09c93

	measure 'Running days' = [SUM of days_running]
		formatString: #,##0
		displayFolder: KPI
		lineageTag: 8373e6b9-6c13-4feb-a227-810c4f453e55

	/// This measure is the average of column 'F_Ad_delivery'[days_running]
	measure 'AVERAGE of days_running' = AVERAGE( F_Ad_delivery[days_running] )
		formatString: #,##0.00
		displayFolder: Aggregations
		lineageTag: defe41ea-f1f1-4dd3-9b55-0a2647e40de8

	measure 'Running days average' = [SUM of days_running]
		formatString: #,##0
		displayFolder: KPI
		lineageTag: 473dd4de-2e3d-44f7-a437-16cff6b207b1

	measure 'No. of Ads' = [DISTINCTCOUNT of _id]
		formatString: #,##0
		displayFolder: KPI
		lineageTag: f1c44507-103b-43e7-9bd7-f14d8717ff9e

	measure 'No. of Payers' = [DISTINCTCOUNT of Payer_key]
		formatString: #,##0
		displayFolder: KPI
		lineageTag: 3c650053-cb6d-4608-a1a3-3e8f9fca697d

	measure 'No. of Pages' = [DISTINCTCOUNT of page_id]
		formatString: #,##0
		displayFolder: KPI
		lineageTag: e5ef932b-bc71-4a66-a7e1-b1a8993cec68

	measure 'No. of Beneficiaries' = ```
			[DISTINCTCOUNT of Beneficiary_key]  
			```
		formatString: #,##0
		displayFolder: KPI
		lineageTag: 05206796-b422-4e9d-9c14-9748d9356b92

	measure 'No. of Bylines' = [DISTINCTCOUNT of Bylines_key]
		formatString: #,##0
		displayFolder: KPI
		lineageTag: f13f7c54-84ac-4792-a179-cea146aee628

	partition Calculations = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlCKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

