table Calculations
	lineageTag: 5185239d-e809-45b5-9983-77077a40aa62

	/// This measure is the sum of column 'F_Demographic_Distribution'[Audience_dem]
	measure 'SUM of Audience_dem' = SUM( F_Demographic_Distribution[Audience_dem] )
		formatString: #,##0.00
		displayFolder: Aggregations
		lineageTag: 098552b1-b387-41db-bbd9-92a4667e24a2

	/// This measure is the sum of column 'F_Demographic_Distribution'[Impressions_dem]
	measure 'SUM of Impressions_dem' = SUM( F_Demographic_Distribution[Impressions_dem] )
		formatString: #,##0.00
		displayFolder: Aggregations
		lineageTag: 85c16d45-714e-4d0c-8ace-b28c88d7556b

	/// This measure is the sum of column 'F_Demographic_Distribution'[Spendings_dem]
	measure 'SUM of Spendings_dem' = SUM( F_Demographic_Distribution[Spendings_dem] )
		formatString: #,##0.00
		displayFolder: Aggregations
		lineageTag: 69871c66-da03-4334-a928-4511ae4aa3b1

	/// This measure is the sum of column 'F_Regional_Distribution'[Audience_reg]
	measure '_SUM of Audience_reg' = SUM( F_Regional_Distribution[Audience_reg] )
		formatString: #,##0.00
		displayFolder: Aggregations
		lineageTag: 1cf555c7-bee3-4cde-b06b-d12efb7df333

	/// This measure is the sum of column 'F_Regional_Distribution'[Impressions_reg]
	measure '_SUM of Impressions_reg' = SUM( F_Regional_Distribution[Impressions_reg] )
		formatString: #,##0.00
		displayFolder: Aggregations
		lineageTag: 70f4588e-1ed9-4a2e-8edf-a91adbc34f6a

	/// This measure is the sum of column 'F_Regional_Distribution'[Spendings_reg]
	measure '_SUM of Spendings_reg' = SUM( F_Regional_Distribution[Spendings_reg] )
		formatString: #,##0.00
		displayFolder: Aggregations
		lineageTag: 9d2a13f4-592f-45ad-86b6-c9c883084d89

	/// This measure is the DISTINCTCOUNT of column 'F_Ad_delivery'[Beneficiary_key]
	measure 'DISTINCTCOUNT of Beneficiary_key' = DISTINCTCOUNT( F_Ad_delivery[Beneficiary_key] )
		formatString: 0.00
		displayFolder: Aggregations
		lineageTag: 72acd3f8-dc97-4ebc-a461-4eea868af9af

	/// This measure is the DISTINCTCOUNT of column 'F_Ad_delivery'[Bylines_key]
	measure 'DISTINCTCOUNT of Bylines_key' = DISTINCTCOUNT( F_Ad_delivery[Bylines_key] )
		formatString: 0.00
		displayFolder: Aggregations
		lineageTag: 83e9787d-416a-4a98-8f42-522a7e84ab86

	/// This measure is the DISTINCTCOUNT of column 'F_Ad_delivery'[Payer_key]
	measure 'DISTINCTCOUNT of Payer_key' = DISTINCTCOUNT( F_Ad_delivery[Payer_key] )
		formatString: 0.00
		displayFolder: Aggregations
		lineageTag: 5b546215-f968-4b24-be48-63311be941e3

	/// This measure is the DISTINCTCOUNT of column 'F_Ad_delivery'[_id]
	measure 'DISTINCTCOUNT of _id' = COUNTROWS(F_Ad_delivery)
		formatString: 0.00
		displayFolder: Aggregations
		lineageTag: de96c2d9-5d4a-413b-8522-e51eaecab80b

	/// This measure is the DISTINCTCOUNT of column 'F_Ad_delivery'[page_id]
	measure 'DISTINCTCOUNT of page_id' = DISTINCTCOUNT( F_Ad_delivery[page_id] )
		formatString: 0.00
		displayFolder: Aggregations
		lineageTag: 546d6dae-7a07-4533-aa8d-60698c51c11b

	/// This measure is the sum of column 'F_Reach_Distribution'[Reach]
	measure 'SUM of Reach' = SUM( F_Reach_Distribution[Reach] )
		formatString: #,##0.00
		displayFolder: Aggregations
		lineageTag: 88c976c7-3874-4eae-bacb-4a8447853592

	/// This measure is the sum of column 'F_Ad_delivery'[eu_total_reach]
	measure 'SUM of eu_total_reach' = SUM( F_Ad_delivery[eu_total_reach] )
		formatString: #,##0.00
		displayFolder: Aggregations
		lineageTag: 60d411cb-aed7-4ed1-b2d5-bff0b69f27c6

	/// This measure is the sum of column 'F_Ad_delivery'[days_running]
	measure 'SUM of days_running' = SUM( F_Ad_delivery[days_running] )
		formatString: #,##0.00
		displayFolder: Aggregations
		lineageTag: 5c75090b-bc1c-4ce4-bfac-c9846ecf21a5

	measure 'Running ads' =
			VAR MinDate = MIN( D_Calendar[Date] )
			VAR MaxDate = MAX( D_Calendar[Date] )
			VAR Result =
			    CALCULATE
			    (
			        COUNTROWS( F_Ad_delivery ),
			        F_Ad_delivery[ad_delivery_start_time] <= MaxDate,
			        F_Ad_delivery[ad_delivery_stop_time] > MinDate,
			        REMOVEFILTERS( D_Calendar )
			    )
			RETURN
			    Result
		formatString: #,##0
		displayFolder: KPI
		lineageTag: 1f30714e-f0c0-4469-953a-f2f30c07dc1a

	measure 'Running ads AVG' = AVERAGEX( D_Calendar, [Running ads] )
		formatString: #,##0.00
		lineageTag: f5ff1369-6fad-415f-9d03-012d9b0514f7

	measure 'Running ads EOP' = CALCULATE( [Running ads], LASTDATE( D_Calendar[Date] ) )
		formatString: #,##0
		lineageTag: ee9695e6-5ca6-40b1-8bdb-67ed11aa9222

	measure 'Started ads' =
			VAR MinDate = MIN( D_Calendar[Date] ) -- Start of the selected period
			VAR MaxDate = MAX( D_Calendar[Date] ) -- End of the selected period
			RETURN
			    CALCULATE
			    (
			        COUNTROWS( F_Ad_delivery ), -- Count ads that overlap the period
			        F_Ad_delivery[ad_delivery_start_time] <= MaxDate, -- Ad starts on or before the end of the period
			        F_Ad_delivery[ad_delivery_stop_time] >= MinDate -- Ad ends on or after the start of the period
			
			    )
		formatString: #,##0
		displayFolder: KPI
		lineageTag: a33c4fbe-3249-46c8-8559-df717d8a38c8

	measure 'Stopped ads' =
			VAR MinDate = MIN( D_Calendar[Date] ) -- Start of the selected period
			VAR MaxDate = MAX( D_Calendar[Date] ) -- End of the selected period
			RETURN
			    CALCULATE
			    (
			        COUNTROWS( F_Ad_delivery ), -- Count ads that overlap the period
			        F_Ad_delivery[ad_delivery_start_time] <= MaxDate, -- Ad starts on or before the end of the period
			        F_Ad_delivery[ad_delivery_stop_time] >= MinDate -- Ad ends on or after the start of the period
			        ,
			        USERELATIONSHIP( D_Calendar[Date], F_Ad_delivery[ad_delivery_stop_time] )
			    )
		formatString: #,##0
		displayFolder: KPI
		lineageTag: cdefe975-5aa6-4c9b-af83-1bf6e13b6107

	measure Audience = IF( ISINSCOPE( D_Region[Region] ), [_SUM of Audience_reg], [SUM of Audience_dem] )
		formatString: #,##0
		displayFolder: KPI
		lineageTag: e577532a-7087-470b-b6b9-a4a72c5504e7

	measure Impressions = IF( ISINSCOPE( D_Region[Region] ), [_SUM of Impressions_reg], [SUM of Impressions_dem] )
		formatString: #,##0
		displayFolder: KPI
		lineageTag: 81e7b016-2305-4453-917b-a4a3c9168b42

	measure Spendings = IF( ISINSCOPE( D_Region[Region] ), [_SUM of Spendings_reg], [SUM of Spendings_dem] )
		formatString: #,##0 "Kč"
		displayFolder: KPI
		lineageTag: 8ad91bb3-3d47-4db3-a3ec-8d964cea171f

	measure Reach = [SUM of Reach]
		formatString: #,##0
		displayFolder: KPI
		lineageTag: aa7270b1-bc71-4765-b004-f6a379c5bdf6

	measure 'Audience per Day' = DIVIDE( [Audience], [Running days] )
		formatString: #,##0
		displayFolder: KPI
		lineageTag: a5648897-daf5-41bb-ae6d-9ae6e3d90e7f

	measure 'Impressions per Day' = DIVIDE( [Impressions], [Running days] )
		formatString: #,##0
		displayFolder: KPI
		lineageTag: d93c0d85-fc63-4747-8979-66c98ea37a20

	measure 'Reach per day' = DIVIDE( [Reach], [Running days] )
		formatString: #,##0
		displayFolder: KPI
		lineageTag: de4fd618-761e-477d-803d-e36dbd971815

	measure 'Spendings per Day' = DIVIDE( [Spendings], [Running days] )
		formatString: #,##0.00 "Kč"
		displayFolder: KPI
		lineageTag: 9aa742c7-ea86-47c3-888c-c169083f6724

	measure 'Running days' = [SUM of days_running]
		formatString: #,##0
		displayFolder: KPI
		lineageTag: 28aae960-bf1a-40f0-aff5-5a2b4209d4ce

	/// This measure is the average of column 'F_Ad_delivery'[days_running]
	measure 'AVERAGE of days_running' = AVERAGE( F_Ad_delivery[days_running] )
		formatString: #,##0.00
		displayFolder: Aggregations
		lineageTag: 39735dbd-abef-4f3a-8c55-6e7c4004dd29

	measure 'Running Days Average' = [AVERAGE of days_running]
		formatString: #,##0.0
		displayFolder: KPI
		lineageTag: 7c1a8ba9-e5d3-4393-adb4-60e95796820b

	measure 'No. of Ads' = ```
			[DISTINCTCOUNT of _id]
			
			
			
			//COUNTROWS(
			//    SUMMARIZE(
			//        F_Demographic_Distribution, F_Demographic_Distribution[_id]
			//    )
			//   
			//)
			```
		formatString: #,##0
		displayFolder: KPI
		lineageTag: 105165ea-f208-462b-9736-0c0194604f0a

	measure 'No. of Payers' = [DISTINCTCOUNT of Payer_key]
		formatString: #,##0
		displayFolder: KPI
		lineageTag: 965e7f84-e8ec-4aa2-b1c6-2a8d2fad40b4

	measure 'No. of Pages' = [DISTINCTCOUNT of page_id]
		formatString: #,##0
		displayFolder: KPI
		lineageTag: 2f838b04-8a3a-4b6d-9a44-0e8fcddee042

	measure 'No. of Beneficiaries' = [DISTINCTCOUNT of Beneficiary_key]
		formatString: #,##0
		displayFolder: KPI
		lineageTag: d77f138a-f51e-4602-bfac-96430ddcc47d

	measure 'No. of Bylines' = [DISTINCTCOUNT of Bylines_key]
		formatString: #,##0
		displayFolder: KPI
		lineageTag: c8ac3a39-4b4b-4e38-b688-78fb06c341be

	/// This measure is the sum of column 'F_Regional_Distribution'[Audience_reg]
	measure '_AVERAGE of Audience_reg' = AVERAGE('F_Regional_Distribution'[Audience_reg])
		formatString: #,##0.00 %
		displayFolder: Aggregations
		lineageTag: 0eae1711-72d8-4818-aecb-bd3a2c9bba3f

	/// This measure is the sum of column 'F_Regional_Distribution'[Impressions_reg]
	measure '_AVERAGE of Impressions_reg' = AVERAGE('F_Regional_Distribution'[Impressions_reg])
		formatString: #,##0.00 %
		displayFolder: Aggregations
		lineageTag: 6725193e-e543-4588-b006-a80a1f3540a5

	/// This measure is the sum of column 'F_Regional_Distribution'[Spendings_reg]
	measure '_AVERAGE of Spendings_reg' = AVERAGE(F_Regional_Distribution[Spendings_reg])
		formatString: #,##0.00 %
		displayFolder: Aggregations
		lineageTag: ca55c07d-ede4-482b-aff8-2405e17da7b6

	/// This measure is the sum of column 'F_Demographic_Distribution'[Audience_dem]
	measure 'AVERAGE of Audience_dem' = AVERAGE( F_Demographic_Distribution[Audience_dem] )
		formatString: #,##0.00
		displayFolder: Aggregations
		lineageTag: 53f8ab8b-1e76-4b62-810c-bc6836cc02f2

	/// This measure is the sum of column 'F_Demographic_Distribution'[Impressions_dem]
	measure 'AVERAGE of Impressions_dem' = AVERAGE('F_Demographic_Distribution'[Impressions_dem])
		formatString: #,##0.00
		displayFolder: Aggregations
		lineageTag: ce6493c7-72e0-4713-8dc5-7979e4506159

	/// This measure is the sum of column 'F_Demographic_Distribution'[Spendings_dem]
	measure 'AVERAGE of Spendings_dem' = AVERAGE('F_Demographic_Distribution'[Spendings_dem])
		formatString: #,##0.00
		displayFolder: Aggregations
		lineageTag: d895a0a2-eb71-42ed-9a40-2876cc59d0b2

	/// This measure is the sum of column 'F_Reach_Distribution'[Reach]
	measure 'AVERAGE of Reach' = AVERAGE('F_Reach_Distribution'[Reach])
		formatString: #,##0.00 %
		displayFolder: Aggregations
		lineageTag: 9c8fce47-b1ee-4ddd-bfd9-857e9c9362c5

	measure 'Audience Average' = IF( ISINSCOPE( D_Region[Region] ), [_AVERAGE of Audience_reg], [AVERAGE of Audience_dem] )
		formatString: #,##0
		displayFolder: KPI
		lineageTag: 755aeec8-7160-4cb9-874b-df8342b1c096

	measure 'Impressions Average' = IF( ISINSCOPE( D_Region[Region] ), [_AVERAGE of Impressions_reg], [AVERAGE of Impressions_dem] )
		formatString: #,##0
		displayFolder: KPI
		lineageTag: 536a2359-5cb3-4e52-a93c-188ede4b6b13

	measure 'Spendings Average' = IF( ISINSCOPE( D_Region[Region] ), [_AVERAGE of Spendings_reg], [AVERAGE of Spendings_dem] )
		formatString: #,##0 "Kč"
		displayFolder: KPI
		lineageTag: 3805a90e-92ef-4184-8117-8ef17db62175

	measure 'Spendings per Impressions' = DIVIDE([Spendings]*1000,[Impressions])
		formatString: #,##0.00 "Kč"
		displayFolder: KPI
		lineageTag: dcbfe70b-06b2-4c90-bcf1-88e5e2e6cfdc

	measure 'Spendings per Ad' = DIVIDE([Spendings],[No. of Ads])
		formatString: #,##0.00 "Kč"
		displayFolder: KPI
		lineageTag: 8bf9dc9f-3e3b-41f4-8941-3300257dfe2f

	measure 'Audience per Ad' = DIVIDE( [Audience], [No. of Ads] )
		formatString: #,##0
		displayFolder: KPI
		lineageTag: f9fdf18e-b61d-4690-beb8-7b837f86504c

	measure 'Impressions per Ad' = DIVIDE( [Impressions], [No. of Ads] )
		formatString: #,##0
		displayFolder: KPI
		lineageTag: 48f7c7c0-5f24-431d-8aae-7681581ec158

	measure 'Spendings per Audience' = DIVIDE([Spendings]*1000,[Audience])
		formatString: #,##0.00 "Kč"
		displayFolder: KPI
		lineageTag: 5683d703-4d80-4c02-a277-f7c7b5046d1f

	measure 'Reach Ratio' = DIVIDE([Impressions],[Reach])
		formatString: #,##0.00
		displayFolder: KPI
		lineageTag: a6844e71-cd46-46fc-bb37-4bbef48b0f53

	measure 'Running ads MoM' =
			VAR _nominator = [Running ads EOP]
			VAR _denominator = [Running ads EOP]-CALCULATE([Running ads EOP], DATEADD(D_Calendar[Date], -1, MONTH))
			VAR result = DIVIDE( _denominator, _nominator, 0 )
			RETURN
			    IF( _denominator = BLANK( ), BLANK( ), result )
		formatString: #,##0.00 %
		lineageTag: 2c925786-1ca0-40b6-ae57-8e3d1f6f4e05

	/// This measure is the sum of column 'F_Ad_delivery'[isRunning]
	measure 'SUM of isRunning' = SUM('F_Ad_delivery'[isRunning])
		formatString: #,##0.00
		displayFolder: Aggregations
		lineageTag: 2b30bc20-bd20-42ed-a3ee-181728c85ceb

	measure 'Active ads' = [SUM of isRunning]
		formatString: #,##0
		displayFolder: KPI
		lineageTag: ce851298-c195-457e-a0a5-15ca60d7a3a4

	measure 'Audience Top' =
			VAR __top1 = TOPN( 1, VALUES( D_Page_name[page_name] ), [Audience], DESC )
			VAR __name = MAXX( __top1, D_Page_name[page_name] )
			VAR __metric = MAXX( __top1, [Audience] )
			RETURN
			"Top: " & __name & " - " & FORMAT( __metric, "#,##0" )
		formatString: #,##0
		displayFolder: KPI
		lineageTag: 73fa6bdc-a2c4-4663-a198-1fc45ba87154

	measure 'Impressions Top' =
			VAR __top1 = TOPN( 1, VALUES( D_Page_name[page_name] ), [Impressions], DESC )
			VAR __name = MAXX( __top1, D_Page_name[page_name] )
			VAR __metric = MAXX( __top1, [Impressions] )
			RETURN
			"Top: " & __name & " - " & FORMAT( __metric, "#,##0" )
		formatString: #,##0
		displayFolder: KPI
		lineageTag: debcac8e-d543-442a-b8f9-540014507de5

	measure 'Reach Top' =
			VAR __top1 = TOPN( 1, VALUES( D_Page_name[page_name] ), [Reach], DESC )
			VAR __name = MAXX( __top1, D_Page_name[page_name] )
			VAR __metric = MAXX( __top1, [Reach] )
			RETURN
			"Top: " & __name & " - " & FORMAT( __metric, "#,##0" )
		formatString: #,##0
		displayFolder: KPI
		lineageTag: 3c3ea967-b421-4a46-bc89-572319347358

	measure 'No. of Ads Top' =
			VAR __top1 = TOPN( 1, VALUES( D_Page_name[page_name] ), [No. of Ads], DESC )
			VAR __name = MAXX( __top1, D_Page_name[page_name] )
			VAR __metric = MAXX( __top1, [No. of Ads] )
			RETURN
			"Top: " & __name & " - " & FORMAT( __metric, "#,##0" )
		formatString: #,##0
		displayFolder: KPI
		lineageTag: a335a42f-549d-400f-b3d2-6b98a1f5c864

	measure 'Spendings Top' =
			VAR __top1 = TOPN( 1, VALUES( D_Page_name[page_name] ), [Spendings], DESC )
			VAR __name = MAXX( __top1, D_Page_name[page_name] )
			VAR __metric = MAXX( __top1, [Spendings] )
			RETURN
			"Top: " & __name & " - " & FORMAT( __metric, "#,##0" )
		formatString: #,##0 "Kč"
		displayFolder: KPI
		lineageTag: e6036f65-dc27-4a4b-b57e-581cdb110991

	measure Conversion = DIVIDE([Impressions],[Audience])
		formatString: #,##0.00 %
		displayFolder: KPI
		lineageTag: c8a93a1a-6586-493f-9aa2-3503d73e7bd0

	measure _pareto_age_selected =
			VAR _total = CALCULATE( [Selected Measure], ALLSELECTED( D_Age_Range[Age_Range] ) )
			VAR _current = [Selected Measure]
			VAR _sumTable =
			    SUMMARIZE( ALLSELECTED( D_Age_Range ), D_Age_Range[Age_Range], "KPI", [Selected Measure] )
			VAR _cummulativeSum =
			    SUMX( FILTER( _sumTable, [Selected Measure] >= _current ), [Selected Measure] )
			RETURN
			    DIVIDE( _cummulativeSum, _total )
		lineageTag: 7b0c20db-592b-49a5-8588-bd62be9a96e2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Spendings per Day All' = ```
			
			
			DIVIDE
			(
			    [Spendings per Day],
			    CALCULATE( [Spendings per Day], ALL( D_Page_name[page_name] ) )
			)
			
			//// calculates a ratio of the difference between value and value of all.
			/// if below 1, then worse than market
			/// if above 1, then better than market
			
			```
		formatString: #,##0.00 "Kč"
		displayFolder: KPI
		lineageTag: a640abc7-59bd-4989-abce-e15fd0e2c215

	measure 'Spendings per Impressions All' = ```
			
			DIVIDE
			(
			    [Spendings per Impressions],
			    CALCULATE( [Spendings per Impressions], ALL( D_Page_name[page_name] ) )
			)
			
			//// calculates a ratio of the difference between value and value of all.
			/// if below 1, then worse than market
			/// if above 1, then better than market
			
			```
		formatString: #,##0.00 "Kč"
		displayFolder: KPI
		lineageTag: 0e49c064-a8fb-494f-9daf-55239a9f6fb2

	measure 'Impressions per Day All' = ```
			DIVIDE
			(
			    [Impressions per Day],
			    CALCULATE( [Impressions per Day], ALL( D_Page_name[page_name] ) )
			)
			
			//// calculates a ratio of the difference between value and value of all.
			/// if below 1, then worse than market
			/// if above 1, then better than market
			
			```
		formatString: #,##0
		displayFolder: KPI
		lineageTag: f5767940-a171-40d1-bea8-d85ba4d60fcc

	measure 'Running Days Average All' = ```
			
			
			DIVIDE
			(
			    [Running Days Average],
			    CALCULATE( [Running Days Average], ALL( D_Page_name[page_name] ) )
			)
			
			//// calculates a ratio of the difference between value and value of all.
			/// if below 1, then worse than market
			/// if above 1, then better than market
			
			```
		formatString: #,##0.0
		displayFolder: KPI
		lineageTag: 231d1fd4-5170-4011-9621-15fc1d418b1c

	measure slicer_detail =
			VAR vAds = [No. of Ads]
			VAR vImpressions = [Impressions]
			VAR vSpendings = [Spendings]
			VAR _NumberFormat =
			    SWITCH
			    (
			        TRUE( ),
			        vSpendings <= 1E3, "#,0.",
			        vSpendings <= 1E4, "#,0,.00 K",
			        vSpendings <= 1E5, "#,0,.0 K",
			        vSpendings <= 1E6, "#,0,. K",
			        vSpendings <= 1E7, "#,0,,.00 M",
			        vSpendings <= 1E8, "#,0,,.0 M",
			        vSpendings <= 1E9, "#,0,,. M"
			    )
			RETURN
			    "Spendings: " & FORMAT( ROUND( vSpendings, 0 ), _NumberFormat ) &
			    " - Impressions: "& FORMAT( ROUND( vImpressions, 0 ), _NumberFormat )&
			    " - Ads: "& vAds
		lineageTag: ea38dd55-d1c6-4501-9420-4e1a7b1e918a

	measure 'Spendings Rank' =
			IF (
			    ISINSCOPE ( D_Page_name[page_name] ),
			    VAR SpendingsCurrentPage = [Spendings]
			    VAR PageRank =
			        RANKX (
			            ALLSELECTED ( D_Page_name ),
			            [Spendings]
			        )
			    VAR Result =
			        IF (
			            NOT ISBLANK ( SpendingsCurrentPage ),
			            PageRank
			        )
			    RETURN
			        Result
			)
		formatString: #,##0
		displayFolder: KPI
		lineageTag: ace26a7e-dfba-4f1f-b58b-7e3a6a8affb5

	measure 'Impressions Rank' =
			IF (
			    HASONEVALUE ( D_Page_name[page_name] ),
			    VAR ImpressionsCurrentPage = [Impressions]
			    VAR PageRank =
			        RANKX (
			            ALLSELECTED ( D_Page_name ),
			            [Impressions]
			        )
			    VAR Result =
			        IF (
			            NOT ISBLANK ( ImpressionsCurrentPage ),
			            PageRank
			        )
			    RETURN
			        Result
			)
		formatString: #,##0
		displayFolder: KPI
		lineageTag: 8c7472da-7d36-4726-810e-854a77c8772d

	measure 'No. of Ads Rank' =
			IF (
			    ISINSCOPE ( D_Page_name[page_name] ),
			    VAR AdsCurrentPage = [No. of Ads]
			    VAR PageRank =
			        RANKX (
			            ALLSELECTED ( D_Page_name ),
			            [No. of Ads]
			        )
			    VAR Result =
			        IF (
			            NOT ISBLANK ( AdsCurrentPage ),
			            PageRank
			        )
			    RETURN
			        Result
			)
		formatString: #,##0
		displayFolder: KPI
		lineageTag: 0c37497c-df64-4eab-8a3f-d7682d13ab34

	/// This measure is the SELECTEDVALUE of column 'F_Ad_delivery'[target_age_range]
	measure 'VALUE of target_age_range' = "Target age: "&SELECTEDVALUE( 'F_Ad_delivery'[target_age_range] )
		displayFolder: Aggregations
		lineageTag: fc2cf0f5-cc36-49c9-a7b7-bd0e391fd020

	/// This measure is the SELECTEDVALUE of column 'D_Payer'[Payer]
	measure 'VALUE of Payer' = "Payer: "&SELECTEDVALUE( 'D_Payer'[Payer] )
		displayFolder: Aggregations
		lineageTag: 4f573c97-695d-4835-9457-574283c379ab

	/// This measure is the SELECTEDVALUE of column 'D_Bylines'[Bylines]
	measure 'VALUE of Bylines' = "Bylines: "&SELECTEDVALUE( 'D_Bylines'[Bylines] )
		displayFolder: Aggregations
		lineageTag: bc306cdc-fa13-4796-86c7-624101774a53

	/// This measure is the SELECTEDVALUE of column 'D_Target_Location'[Target_Location]
	measure 'VALUE of Target_Location' = "Target location: "&SELECTEDVALUE( 'D_Target_Location'[Target_Location] )
		displayFolder: Aggregations
		lineageTag: 15f4ecb6-e80e-4445-8c32-e77ba9787d6c

	/// This measure is the SELECTEDVALUE of column 'D_Ad_Content'[Ad_Content]
	measure 'VALUE of Ad_Content' =
			IF(
			    ISBLANK(SELECTEDVALUE( 'D_Ad_Content'[Ad_Content] )),"No content provided",SELECTEDVALUE( 'D_Ad_Content'[Ad_Content] )
			)
		displayFolder: Aggregations
		lineageTag: 63a2eb9e-84b4-41a1-acfb-cc278e8e1867

	/// This measure is the SELECTEDVALUE of column 'F_Ad_delivery'[target_gender]
	measure 'VALUE of target_gender' = SELECTEDVALUE( 'F_Ad_delivery'[target_gender] )
		displayFolder: Aggregations
		lineageTag: a4a3cbbd-9cf7-4c9c-8de0-f7c2aa50f063

	measure _slicer = COUNTROWS(F_Ad_delivery)
		formatString: 0
		lineageTag: cfe1cbf6-c6d1-4e6c-9a38-c49a885e76a2

	measure top_age_range =
			VAR __top1 = TOPN( 1, VALUES( D_Age_Range[Age_Range] ), [Spendings], DESC )
			VAR __name = MAXX( __top1, D_Age_Range[Age_Range] )
			RETURN
			 __name & " age group"
		lineageTag: 9da2bf5a-b3a3-43d0-838d-14f1d4bb9493

		formatStringDefinition =
				VAR _value = [Metric Selected Title] RETURN SWITCH
				(
				    TRUE( ),
				    _value = "Margin %", "0.0%",
				    "#,#0"
				)

	measure top_gender =
			VAR __top1 = TOPN( 1, VALUES( D_Gender[Gender] ), [Spendings], DESC )
			VAR __name = MAXX( __top1, D_Gender[Gender] )
			RETURN
			 __name & " gender"
		lineageTag: 8898e35c-dba0-4aee-82f5-3f80896e19f4

		formatStringDefinition =
				VAR _value = [Metric Selected Title] RETURN SWITCH
				(
				    TRUE( ),
				    _value = "Margin %", "0.0%",
				    "#,#0"
				)

	measure top_region =
			VAR __top1 = TOPN( 1, VALUES( D_Region[Region_short] ), [Spendings], DESC )
			VAR __name = MAXX( __top1, D_Region[Region_short] )
			RETURN
			 __name
		lineageTag: 4047e83a-3d67-4603-9c9b-3519b96ecc47

		formatStringDefinition =
				VAR _value = [Metric Selected Title] RETURN SWITCH
				(
				    TRUE( ),
				    _value = "Margin %", "0.0%",
				    "#,#0"
				)

	measure 'Spendings All Regions (%)' = ```
			DIVIDE
			(
			    [_SUM of Spendings_reg],
			    CALCULATE( [_SUM of Spendings_reg], ALL( D_Region[Region] )
			        
			    )
			)
			```
		formatString: 0.00%
		displayFolder: KPI
		lineageTag: 5ce62641-fc33-4d81-ad26-b078f854051b

	measure 'Spendings All Regions ' = CALCULATE( [_SUM of Spendings_reg], ALL( D_Region[Region] ) )
		formatString: #,##0.00 "Kč"
		displayFolder: KPI
		lineageTag: 54d71dbd-f845-4f15-a0d1-633a549ed7cc

	measure 'Spendings All Pages (%)' = ```
			DIVIDE
			(
			    [_SUM of Spendings_reg],
			    CALCULATE( [_SUM of Spendings_reg], ALLSELECTED(D_Page_name[page_name])
			        
			    )
			)
			```
		formatString: 0.00%
		displayFolder: KPI
		lineageTag: dc0b55fe-5d32-4c26-8144-047ebf06673b

	measure slicer_detail-cs =
			VAR vAds = [No. of Ads]
			VAR vImpressions = [Impressions]
			VAR vSpendings = [Spendings]
			VAR _NumberFormat =
			    SWITCH
			    (
			        TRUE( ),
			        vSpendings <= 1E3, "#,0.",
			        vSpendings <= 1E4, "#,0,.00 K",
			        vSpendings <= 1E5, "#,0,.0 K",
			        vSpendings <= 1E6, "#,0,. K",
			        vSpendings <= 1E7, "#,0,,.00 M",
			        vSpendings <= 1E8, "#,0,,.0 M",
			        vSpendings <= 1E9, "#,0,,. M"
			    )
			RETURN
			    "Výdaje: " & FORMAT( ROUND( vSpendings, 0 ), _NumberFormat ) &
			    " - Zobrazení: "& FORMAT( ROUND( vImpressions, 0 ), _NumberFormat )&
			    " - Reklamy: "& vAds
		lineageTag: a094753f-81e3-4aa6-8232-13d8010c0df7

	measure Name = ```
			
			SWITCH(
			    TRUE(),
			    
			    ISINSCOPE(D_Page_name[url_key]),SELECTEDVALUE(D_Page_name[page_name]),
			    ISINSCOPE(parties_urls[url_key]),SELECTEDVALUE(D_Bylines[Bylines_grp]),BLANK())
			    
			```
		lineageTag: dab11fda-e045-49a1-9dbb-baea00db0504

	measure 'Gauge with Outline' =
			
			VAR MAXValue = 1 // enter value or measure
			VAR CounterValue =
			    DIVIDE (
			        [Spendings],
			        CALCULATE (
			            [Spendings],
			            ALL ( D_Bylines[Bylines_grp] ),
			            KEEPFILTERS ( D_Bylines[is_political] = "1" )
			        )
			    ) // enter value or measure
			VAR AXISRANGE =
			    MAXX ( { MAXValue, CounterValue }, [Value] )
			VAR TRACKWIDTH = MAXValue / AXISRANGE * 100
			VAR PERCENTAGEFILL = CounterValue / AXISRANGE
			RETURN
			    "data:image/svg+xml;charset=utf-8,<svg xmlns='http://www.w3.org/2000/svg'
			    xmlns:xlink='http://www.w3.org/1999/xlink' width='160' height='100' display='block' viewBox='0 0 100 80' overflow='visible'>
			    <path id='track' fill='none' stroke='lightgrey' stroke-opacity='0.1' d='M10,55 a45,45 0 1 1 90,0' stroke-width='20'/>
			    <path id='fill' fill='none' stroke-opacity='0.3' stroke="
			        & IF (
			            PERCENTAGEFILL < 0.50,
			            "'red'",
			            IF ( PERCENTAGEFILL < 0.65, "'yellow'", "'green'" )
			        ) & " d='M10,55 a45,45 0 1 1 90,0' stroke-width='20' stroke-dasharray='141.3717' stroke-dashoffset=" & "'"
			        & ( 1 - PERCENTAGEFILL )
			            * ( PI () * 45 ) & "'" & "></path>
			<path id='track' fill='none' stroke='gray' stroke-opacity='1' d='M4,55 a45,45 0 1 1 102,0' stroke-width='6' transform='translate(0 0)'/>
			<path id='dialoutline' fill='none' stroke='white' d='M0,55 L55,55' stroke-width='5' transform='rotate(" & PERCENTAGEFILL * 180 & " 55 55)'/>
			<path id='dial' fill='none' stroke='black' d='M0,55 L55,55' stroke-width='3' stroke-linecap='round' transform='rotate(" & PERCENTAGEFILL * 180 & " 55 55)'/>
			<text x='55' y='75' text-anchor='middle' font-family='Segoe UI' font-size='20' font-weight='bold'>"
			        & FORMAT ( PERCENTAGEFILL, "0%" ) & "</text>
			</svg>
			"
		lineageTag: 2681212f-86db-43c1-9b83-eab2bf181f32
		dataCategory: ImageUrl

	partition Calculations = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlCKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

