table D_Ad_Content
	lineageTag: 84562674-9f0e-484b-8b86-58879ae1648b

	column Ad_Content
		dataType: string
		isHidden
		lineageTag: fcdd350e-fa40-4630-9518-11d19740cded
		summarizeBy: none
		sourceColumn: Ad_Content

		annotation SummarizationSetBy = Automatic

	column Ad_Content_key
		dataType: int64
		formatString: 0
		lineageTag: 849947c7-d10c-46eb-aabe-67c5c2d88b42
		summarizeBy: none
		sourceColumn: Ad_Content_key

		annotation SummarizationSetBy = Automatic

	partition D_Ad_Content = m
		mode: import
		queryGroup: DIMs
		source =
				let
				    Source = Odbc.DataSource("dsn=spending_db", [HierarchicalNavigation=true]),
				    spending_db_Database = Source{[Name="spending_db",Kind="Database"]}[Data],
				    v_spending_View = spending_db_Database{[Name="v_spending",Kind="View"]}[Data],
				    #"Cleaned Text" = Table.TransformColumns(v_spending_View,{{"payer", Text.Clean, type text}, {"page_name", Text.Clean, type text}, {"bylines", Text.Clean, type text}, {"beneficiary", Text.Clean, type text}, {"ad_creative_bodies", Text.Clean, type text}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Cleaned Text",{{"payer", Text.Trim, type text}, {"page_name", Text.Trim, type text}, {"bylines", Text.Trim, type text}, {"beneficiary", Text.Trim, type text}, {"ad_creative_bodies", Text.Trim, type text}}),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Trimmed Text",{{"payer", Text.Proper, type text}, {"page_name", Text.Proper, type text}, {"bylines", Text.Proper, type text}, {"beneficiary", Text.Proper, type text}, {"ad_creative_bodies", Text.Proper, type text}}),
				    ad_creative_bodies1 = #"Capitalized Each Word"[ad_creative_bodies],
				    #"Removed Duplicates" = List.Distinct(ad_creative_bodies1),
				    #"Sorted Items" = List.Sort(#"Removed Duplicates",Order.Ascending),
				    #"Converted to Table" = Table.FromList(#"Sorted Items", Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Added Index" = Table.AddIndexColumn(#"Converted to Table", "Index", 0, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Column1", "Ad_Content"}, {"Index", "Ad_Content_key"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation TabularEditor_TableGroup = DIMs

