table D_Beneficiary
	lineageTag: b5816bfc-67da-4eb0-b085-18fedf57ff93

	column Beneficiary
		dataType: string
		lineageTag: d1d3a72a-3390-4f6c-9d6c-38c74d6c6cb9
		summarizeBy: none
		sourceColumn: Beneficiary

		annotation SummarizationSetBy = Automatic

	column Beneficiary_key
		dataType: int64
		formatString: 0
		lineageTag: 3056cf10-088a-4676-a5ac-c8da1526dd1e
		summarizeBy: none
		sourceColumn: Beneficiary_key

		annotation SummarizationSetBy = Automatic

	partition D_Beneficiary = m
		mode: import
		source =
				let
				    Source = Odbc.DataSource("dsn=political_ads", [HierarchicalNavigation=true]),
				    political_ads_db_Database = Source{[Name="political_ads_db",Kind="Database"]}[Data],
				    political_ads_Table = political_ads_db_Database{[Name="political_ads",Kind="Table"]}[Data],
				    #"Cleaned Text" = Table.TransformColumns(political_ads_Table,{{"payer", Text.Clean, type text}, {"page_name", Text.Clean, type text}, {"bylines", Text.Clean, type text}, {"beneficiary", Text.Clean, type text}, {"ad_creative_bodies", Text.Clean, type text}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Cleaned Text",{{"payer", Text.Trim, type text}, {"page_name", Text.Trim, type text}, {"bylines", Text.Trim, type text}, {"beneficiary", Text.Trim, type text}, {"ad_creative_bodies", Text.Trim, type text}}),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Trimmed Text",{{"payer", Text.Proper, type text}, {"page_name", Text.Proper, type text}, {"bylines", Text.Proper, type text}, {"beneficiary", Text.Proper, type text}, {"ad_creative_bodies", Text.Proper, type text}}),
				    beneficiary1 = #"Capitalized Each Word"[beneficiary],
				    #"Removed Duplicates" = List.Distinct(beneficiary1),
				    #"Sorted Items" = List.Sort(#"Removed Duplicates",Order.Ascending),
				    #"Converted to Table" = Table.FromList(#"Sorted Items", Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Added Index" = Table.AddIndexColumn(#"Converted to Table", "Index", 0, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Column1", "Beneficiary"}, {"Index", "Beneficiary_key"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation TabularEditor_TableGroup = DIMs

