table D_Page_name
	lineageTag: d674e412-43da-45e4-a766-a5cda381745c

	measure Measure = SELECTEDVALUE(D_Page_name[url_key])
		lineageTag: 5abc0f8f-194a-4590-9ff2-2ba7aa53f0d1

	column page_name
		dataType: string
		lineageTag: 8d522888-3dcb-4d2b-8593-fabcfe85d2d8
		summarizeBy: none
		sourceColumn: page_name

		annotation SummarizationSetBy = Automatic

	column page_id
		dataType: string
		lineageTag: 3f791c18-0888-4144-a174-157e283df20a
		summarizeBy: none
		sourceColumn: page_id

		annotation SummarizationSetBy = Automatic

	column url_key
		dataType: string
		lineageTag: c66dc86d-23cc-462a-8365-7c9ddba9cd1a
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: url_key

		annotation SummarizationSetBy = Automatic

	partition D_Page_name = m
		mode: import
		queryGroup: DIMs
		source =
				let
				    Source = Odbc.DataSource("dsn=spending_db", [HierarchicalNavigation=true]),
				    spending_db_Database = Source{[Name="spending_db",Kind="Database"]}[Data],
				    v_spending_View = spending_db_Database{[Name="v_spending",Kind="View"]}[Data],
				    #"Cleaned Text" = Table.TransformColumns(v_spending_View,{{"payer", Text.Clean, type text}, {"page_name", Text.Clean, type text}, {"bylines", Text.Clean, type text}, {"beneficiary", Text.Clean, type text}, {"ad_creative_bodies", Text.Clean, type text}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Cleaned Text",{{"payer", Text.Trim, type text}, {"page_name", Text.Trim, type text}, {"bylines", Text.Trim, type text}, {"beneficiary", Text.Trim, type text}, {"ad_creative_bodies", Text.Trim, type text}}),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Trimmed Text",{{"payer", Text.Proper, type text}, {"page_name", Text.Proper, type text}, {"bylines", Text.Proper, type text}, {"beneficiary", Text.Proper, type text}, {"ad_creative_bodies", Text.Proper, type text}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Capitalized Each Word",{"page_name", "page_id"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns", {"page_id"}),
				    #"Extracted Text Before Delimiter" = Table.TransformColumns(#"Removed Duplicates", {{"page_name", each Text.BeforeDelimiter(_, " - "), type text}}),
				    #"Merged Queries" = Table.NestedJoin(#"Extracted Text Before Delimiter", {"page_id"}, image_urls, {"page_id"}, "image_urls", JoinKind.LeftOuter),
				    #"Expanded image_urls" = Table.ExpandTableColumn(#"Merged Queries", "image_urls", {"url_key"}, {"url_key"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Expanded image_urls","Greenpeace Česká Republika","Greenpeace ČR",Replacer.ReplaceText,{"page_name"})
				in
				    #"Replaced Value"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation TabularEditor_TableGroup = DIMs

