table D_Payer
	lineageTag: 6022980b-1c31-478d-8b90-f662427ad24e

	column Payer
		dataType: string
		lineageTag: 3b48cc2f-503a-4b9d-a7cc-3d77cc718094
		summarizeBy: none
		sourceColumn: Payer

		annotation SummarizationSetBy = Automatic

	column Payer_key
		dataType: int64
		formatString: 0
		lineageTag: 68614249-1c42-49fb-8ead-7875800c7624
		summarizeBy: none
		sourceColumn: Payer_key

		annotation SummarizationSetBy = Automatic

	partition D_Payer = m
		mode: import
		source =
				let
				    Source = Odbc.DataSource("dsn=political_ads", [HierarchicalNavigation=true]),
				    political_ads_db_Database = Source{[Name="political_ads_db",Kind="Database"]}[Data],
				    political_ads_Table = political_ads_db_Database{[Name="political_ads",Kind="Table"]}[Data],
				    #"Cleaned Text" = Table.TransformColumns(political_ads_Table,{{"payer", Text.Clean, type text}, {"page_name", Text.Clean, type text}, {"bylines", Text.Clean, type text}, {"beneficiary", Text.Clean, type text}, {"ad_creative_bodies", Text.Clean, type text}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Cleaned Text",{{"payer", Text.Trim, type text}, {"page_name", Text.Trim, type text}, {"bylines", Text.Trim, type text}, {"beneficiary", Text.Trim, type text}, {"ad_creative_bodies", Text.Trim, type text}}),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Trimmed Text",{{"payer", Text.Proper, type text}, {"page_name", Text.Proper, type text}, {"bylines", Text.Proper, type text}, {"beneficiary", Text.Proper, type text}, {"ad_creative_bodies", Text.Proper, type text}}),
				    payer1 = #"Capitalized Each Word"[payer],
				    #"Removed Duplicates" = List.Distinct(payer1),
				    #"Sorted Items" = List.Sort(#"Removed Duplicates",Order.Ascending),
				    #"Converted to Table" = Table.FromList(#"Sorted Items", Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Added Index" = Table.AddIndexColumn(#"Converted to Table", "Index", 0, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Column1", "Payer"}, {"Index", "Payer_key"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation TabularEditor_TableGroup = DIMs

