table D_Region
	lineageTag: d5db46de-7f57-46e7-aab6-025d14651ef9

	column Region
		dataType: string
		lineageTag: e052ebcb-35fd-4d93-94be-9ba26d3fcd41
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Region_key
		dataType: string
		lineageTag: 2d28b572-6b4d-4856-9da7-1cec533ca78c
		summarizeBy: none
		sourceColumn: Region_key

		annotation SummarizationSetBy = Automatic

	partition D_Region = m
		mode: import
		queryGroup: DIMs
		source =
				let
				    Source = Odbc.DataSource("dsn=political_ads_db", [HierarchicalNavigation=true]),
				    political_ads_db_Database = Source{[Name="political_ads_db",Kind="Database"]}[Data],
				    political_ads_delivery_by_region_Table = political_ads_db_Database{[Name="political_ads_delivery_by_region",Kind="Table"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(political_ads_delivery_by_region_Table, each ([delivery_by_region.percentage] <> null)),
				    #"delivery_by_region region1" = #"Filtered Rows"[delivery_by_region.region],
				    #"Removed Duplicates" = List.Distinct(#"delivery_by_region region1"),
				    #"Sorted Items" = List.Sort(#"Removed Duplicates",Order.Ascending),
				    #"Converted to Table" = Table.FromList(#"Sorted Items", Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Added Index" = Table.AddIndexColumn(#"Converted to Table", "Index", 0, 1, Int64.Type),
				    #"Renamed Columns" = #table(
				        {"Region", "Region_key"},
				        {
				{"Central Bohemian Region",0},
				{"Hradec Králové Region",1},
				{"Karlovy Vary Region",2},
				{"Liberec Region",3},
				{"Moravian-Silesian Region",4},
				{"Olomouc Region",5},
				{"Pardubice Region",6},
				{"Plzeň Region",7},
				{"Prague",8},
				{"South Bohemian Region",9},
				{"South Moravian Region",10},
				{"Ústí nad Labem Region",13},
				{"Vysočina Region",11},
				{"Zlín Region",12}
				        }
				    )
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation TabularEditor_TableGroup = DIMs

