table D_Target_Location
	lineageTag: 35050d05-8553-400c-aac7-113ab681f9c7

	column Target_Location
		dataType: string
		isHidden
		lineageTag: b9b9333b-79d6-423a-a82a-b23f0736d208
		summarizeBy: none
		sourceColumn: Target_Location

		annotation SummarizationSetBy = Automatic

	column Target_Location_key
		dataType: int64
		formatString: 0
		lineageTag: 1135a565-de7a-4241-90ba-cd225058a3b2
		summarizeBy: none
		sourceColumn: Target_Location_key

		annotation SummarizationSetBy = Automatic

	partition D_Target_Location = m
		mode: import
		queryGroup: DIMs
		source =
				let
				    Source = Odbc.DataSource("dsn=spending_db", [HierarchicalNavigation=true]),
				    spending_db_Database = Source{[Name="spending_db",Kind="Database"]}[Data],
				    v_spending_View = spending_db_Database{[Name="v_spending",Kind="View"]}[Data],
				    #"Cleaned Text" = Table.TransformColumns(v_spending_View,{{"payer", Text.Clean, type text}, {"page_name", Text.Clean, type text}, {"bylines", Text.Clean, type text}, {"beneficiary", Text.Clean, type text}, {"ad_creative_bodies", Text.Clean, type text}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Cleaned Text",{{"payer", Text.Trim, type text}, {"page_name", Text.Trim, type text}, {"bylines", Text.Trim, type text}, {"beneficiary", Text.Trim, type text}, {"ad_creative_bodies", Text.Trim, type text}}),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Trimmed Text",{{"payer", Text.Proper, type text}, {"page_name", Text.Proper, type text}, {"bylines", Text.Proper, type text}, {"beneficiary", Text.Proper, type text}, {"ad_creative_bodies", Text.Proper, type text}}),
				    target_location_name1 = #"Capitalized Each Word"[target_location_name],
				    #"Removed Duplicates" = List.Distinct(target_location_name1),
				    #"Sorted Items" = List.Sort(#"Removed Duplicates",Order.Ascending),
				    #"Converted to Table" = Table.FromList(#"Sorted Items", Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Added Index" = Table.AddIndexColumn(#"Converted to Table", "Index", 0, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Column1", "Target_Location"}, {"Index", "Target_Location_key"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

	annotation TabularEditor_TableGroup = DIMs

