table F_Ad_delivery
	lineageTag: e0ff1399-a77f-482c-b387-a3ba2d86c1d5

	column _id
		dataType: string
		lineageTag: 97d641a2-18c4-4d8e-9b63-4a3187af1f02
		summarizeBy: none
		sourceColumn: _id

		annotation SummarizationSetBy = Automatic

	column ad_delivery_start_time
		dataType: dateTime
		formatString: dd-mmm-yy
		lineageTag: 457daa65-9552-4cf7-bc73-809e73a9f1ad
		summarizeBy: none
		sourceColumn: ad_delivery_start_time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column ad_delivery_stop_time
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7e32746c-8bbf-4764-a154-0017bd5f480e
		summarizeBy: none
		sourceColumn: ad_delivery_stop_time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column currency
		dataType: string
		lineageTag: ba8c44d5-e4d2-4928-a3aa-e264cd21d787
		summarizeBy: none
		sourceColumn: currency

		annotation SummarizationSetBy = Automatic

	column eu_total_reach
		dataType: int64
		formatString: 0
		lineageTag: 68e6c16e-75c0-49f2-a7be-e06f04eef6f5
		summarizeBy: sum
		sourceColumn: eu_total_reach

		annotation SummarizationSetBy = Automatic

	column languages
		dataType: string
		lineageTag: c3033c99-cab9-4df6-bb2a-a6a17ed15f52
		summarizeBy: none
		sourceColumn: languages

		annotation SummarizationSetBy = Automatic

	column page_id
		dataType: string
		lineageTag: 45264652-4139-45d2-9042-348954442dc8
		summarizeBy: none
		sourceColumn: page_id

		annotation SummarizationSetBy = Automatic

	column publisher_platforms
		dataType: string
		lineageTag: 3485cbcc-693d-4b48-affd-f2901ee0478a
		summarizeBy: none
		sourceColumn: publisher_platforms

		annotation SummarizationSetBy = Automatic

	column target_ages_bot
		dataType: string
		lineageTag: 8542d717-7b8f-4b8a-9c6b-469b9fd419cd
		summarizeBy: none
		sourceColumn: target_ages_bot

		annotation SummarizationSetBy = Automatic

	column target_ages_top
		dataType: string
		lineageTag: 7f77efcb-3b6e-47e9-93c3-ef81492b6ec0
		summarizeBy: none
		sourceColumn: target_ages_top

		annotation SummarizationSetBy = Automatic

	column target_gender
		dataType: string
		isHidden
		lineageTag: a1d6d25b-e16c-45c2-a6a5-0805c3b52311
		summarizeBy: none
		sourceColumn: target_gender

		annotation SummarizationSetBy = Automatic

	column target_location_type
		dataType: string
		lineageTag: 62effcf9-43d8-474d-9c84-458af6ad5122
		summarizeBy: none
		sourceColumn: target_location_type

		annotation SummarizationSetBy = Automatic

	column Ad_Content_key
		dataType: int64
		formatString: 0
		lineageTag: 9840a853-2db6-4954-be1f-9284600510ce
		summarizeBy: none
		sourceColumn: Ad_Content_key

		annotation SummarizationSetBy = Automatic

	column Beneficiary_key
		dataType: int64
		formatString: 0
		lineageTag: 5d2454a0-674e-4050-b804-222b4c1e0419
		summarizeBy: none
		sourceColumn: Beneficiary_key

		annotation SummarizationSetBy = Automatic

	column Bylines_key
		dataType: int64
		formatString: 0
		lineageTag: 593313aa-fb38-4833-bbe8-f895f3c4510c
		summarizeBy: none
		sourceColumn: Bylines_key

		annotation SummarizationSetBy = Automatic

	column Payer_key
		dataType: int64
		formatString: 0
		lineageTag: 876e5039-c3e8-4e19-b66c-674d1268c3b5
		summarizeBy: none
		sourceColumn: Payer_key

		annotation SummarizationSetBy = Automatic

	column Target_Location_key
		dataType: int64
		formatString: 0
		lineageTag: 4e853f92-f3ab-4c0c-893c-ccbd3cbf81c0
		summarizeBy: none
		sourceColumn: Target_Location_key

		annotation SummarizationSetBy = Automatic

	column days_running = ```
			//VAR _max =
			//    CALCULATE
			//    (
			//        MAX( F_Ad_delivery[ad_delivery_start_time] ),
			//        ALL( F_Ad_delivery[ad_delivery_start_time] )
			//    )
			//RETURN
			//    IF
			//    (
			//        F_Ad_delivery[ad_delivery_stop_time] > TODAY( ),
			//        DATEDIFF( F_Ad_delivery[ad_delivery_start_time], _max, DAY ),
			//        DATEDIFF( F_Ad_delivery[ad_delivery_start_time], F_Ad_delivery[ad_delivery_stop_time], DAY )
			//        )
			
			DATEDIFF( F_Ad_delivery[ad_delivery_start_time], F_Ad_delivery[ad_delivery_stop_time], DAY )+1
			
			```
		isHidden
		lineageTag: af908ee7-7fdc-46e3-8a71-42dbed4c509a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column isRunning
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 34b4349f-b0df-449a-836c-c6baae8445f9
		summarizeBy: sum
		sourceColumn: isRunning

		annotation SummarizationSetBy = Automatic

	column target_age_range = F_Ad_delivery[target_ages_bot]&" - "&F_Ad_delivery[target_ages_top]
		isHidden
		lineageTag: 9b9c99a4-a380-47e9-99bb-43278ac7de1b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Ad_Title_key
		dataType: int64
		formatString: 0
		lineageTag: 017b539a-1a5c-4e73-bfcb-96afd097bbd9
		summarizeBy: none
		sourceColumn: Ad_Title_key

		annotation SummarizationSetBy = Automatic

	partition F_Ad_delivery = m
		mode: import
		queryGroup: FACTs
		source =
				let
				    Source = Odbc.DataSource("dsn=spending_db", [HierarchicalNavigation=true]),
				    spending_db_Database = Source{[Name="spending_db",Kind="Database"]}[Data],
				    v_spending_View = spending_db_Database{[Name="v_spending",Kind="View"]}[Data],
				    #"Removed Other Columns1" = Table.SelectColumns(v_spending_View,{"_id", "ad_creation_time", "ad_creative_bodies","ad_creative_link_titles", "ad_delivery_start_time", "ad_delivery_stop_time", "average_audience_size", "average_impressions", "average_spend", "beneficiary", "bylines", "currency", "eu_total_reach", "languages", "page_id", "page_name", "payer", "publisher_platforms", "target_ages_bot", "target_ages_top", "target_gender", "target_location_name", "target_location_type"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Removed Other Columns1", null, each [bylines], Replacer.ReplaceValue, {"payer"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1",null, each [bylines], Replacer.ReplaceValue, {"beneficiary"}),
				    #"Cleaned Text" = Table.TransformColumns(#"Replaced Value2",{{"payer", Text.Clean, type text}, {"page_name", Text.Clean, type text}, {"bylines", Text.Clean, type text}, {"beneficiary", Text.Clean, type text}, {"ad_creative_link_titles", Text.Clean, type text}, {"ad_creative_bodies", Text.Clean, type text}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Cleaned Text",{{"payer", Text.Trim, type text}, {"page_name", Text.Trim, type text}, {"bylines", Text.Trim, type text}, {"beneficiary", Text.Trim, type text}, {"ad_creative_link_titles", Text.Trim, type text}, {"ad_creative_bodies", Text.Trim, type text}}),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Trimmed Text",{{"payer", Text.Proper, type text}, {"page_name", Text.Proper, type text}, {"bylines", Text.Proper, type text}, {"beneficiary", Text.Proper, type text}, {"ad_creative_link_titles", Text.Proper, type text}, {"ad_creative_bodies", Text.Proper, type text}}),
				    #"Merged Queries" = Table.NestedJoin(#"Capitalized Each Word", {"ad_creative_bodies"}, D_Ad_Content, {"Ad_Content"}, "D_Ad_Content", JoinKind.LeftOuter),
				    #"Merged Queries1" = Table.NestedJoin(#"Merged Queries", {"beneficiary"}, D_Beneficiary, {"Beneficiary"}, "D_Beneficiary", JoinKind.LeftOuter),
				    #"Merged Queries2" = Table.NestedJoin(#"Merged Queries1", {"bylines"}, D_Bylines, {"Bylines"}, "D_Bylines", JoinKind.LeftOuter),
				    #"Merged Queries3" = Table.NestedJoin(#"Merged Queries2", {"payer"}, D_Payer, {"Payer"}, "D_Payer", JoinKind.LeftOuter),
				    #"Merged Queries4" = Table.NestedJoin(#"Merged Queries3", {"target_location_name"}, D_Target_Location, {"Target_Location"}, "D_Target_Location", JoinKind.LeftOuter),
				    #"Merged Queries5" = Table.NestedJoin(#"Merged Queries4", {"ad_creative_link_titles"}, D_Ad_Title, {"Ad_Title"}, "D_Ad_Title", JoinKind.LeftOuter),
				    #"Removed Other Columns" = Table.SelectColumns(#"Merged Queries5",{"_id", "ad_delivery_start_time", "ad_delivery_stop_time", "currency", "eu_total_reach", "languages", "page_id", "publisher_platforms", "target_ages_bot", "target_ages_top", "target_gender", "target_location_type", "D_Ad_Content", "D_Beneficiary", "D_Bylines", "D_Payer", "D_Target_Location", "D_Ad_Title"}),
				    #"Expanded D_Ad_Content" = Table.ExpandTableColumn(#"Removed Other Columns", "D_Ad_Content", {"Ad_Content_key"}, {"Ad_Content_key"}),
				    #"Expanded D_Beneficiary" = Table.ExpandTableColumn(#"Expanded D_Ad_Content", "D_Beneficiary", {"Beneficiary_key"}, {"Beneficiary_key"}),
				    #"Expanded D_Bylines" = Table.ExpandTableColumn(#"Expanded D_Beneficiary", "D_Bylines", {"Bylines_key"}, {"Bylines_key"}),
				    #"Expanded D_Payer" = Table.ExpandTableColumn(#"Expanded D_Bylines", "D_Payer", {"Payer_key"}, {"Payer_key"}),
				    #"Expanded D_Target_Location" = Table.ExpandTableColumn(#"Expanded D_Payer", "D_Target_Location", {"Target_Location_key"}, {"Target_Location_key"}),
				    #"Expanded D_Ad_Title" = Table.ExpandTableColumn(#"Expanded D_Target_Location", "D_Ad_Title", {"Ad_Title_key"}, {"Ad_Title_key"}),
				    #"Added Custom" = Table.AddColumn(#"Expanded D_Ad_Title", "isRunning", each if[ad_delivery_stop_time] is null then 1 else 0,Int64.Type),
				    MaxStopTime = List.Max(List.RemoveNulls(#"Added Custom"[ad_delivery_stop_time])),
				    #"Replaced Value" = Table.ReplaceValue(#"Added Custom", null, MaxStopTime, Replacer.ReplaceValue, {"ad_delivery_stop_time"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{{"ad_delivery_start_time", type date}, {"ad_delivery_stop_time", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation TabularEditor_TableGroup = FACTs

