table F_Demographic_Distribution
	lineageTag: b877e318-8a7f-4956-820a-912e30d0fcad

	column _id
		dataType: string
		lineageTag: 5ae93992-3909-4386-b057-e65f9e48b78c
		summarizeBy: none
		sourceColumn: _id

		annotation SummarizationSetBy = Automatic

	column Age_Range_key
		dataType: string
		lineageTag: ef219f0c-f76e-4797-b6f3-5ec85f489c1e
		summarizeBy: none
		sourceColumn: Age_Range_key

		annotation SummarizationSetBy = Automatic

	column Gender_key
		dataType: string
		lineageTag: b2612d1d-7e7c-467f-8629-9bdee7cbc4bd
		summarizeBy: none
		sourceColumn: Gender_key

		annotation SummarizationSetBy = Automatic

	column Audience_dem
		dataType: double
		isHidden
		lineageTag: 0f430c12-8220-49ae-a588-6384b07ad02b
		summarizeBy: sum
		sourceColumn: Audience_dem

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Impressions_dem
		dataType: double
		isHidden
		lineageTag: 1430c46c-2ff4-47c3-8124-6ececb3dc411
		summarizeBy: sum
		sourceColumn: Impressions_dem

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Spendings_dem
		dataType: double
		isHidden
		lineageTag: 7b881e32-55c5-4e4f-8b1c-74c5082e3a4f
		summarizeBy: sum
		sourceColumn: Spendings_dem

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition F_Demographic_Distribution = m
		mode: import
		queryGroup: FACTs
		source =
				let
				    Source = Odbc.DataSource("dsn=spending_db", [HierarchicalNavigation=true]),
				    spending_db_Database = Source{[Name="spending_db",Kind="Database"]}[Data],
				    v_spending_demographic_distribution_View = spending_db_Database{[Name="v_spending_demographic_distribution",Kind="View"]}[Data],
				    #"Replaced Value" = Table.ReplaceValue(v_spending_demographic_distribution_View,null,"All",Replacer.ReplaceValue,{"demographic_distribution.age", "demographic_distribution.gender"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",null,"1",Replacer.ReplaceValue,{"demographic_distribution.percentage"}),
				    #"Filtered Rows" = Table.SelectRows(#"Replaced Value1", each ([demographic_distribution.age] <> null)),
				    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows", {"demographic_distribution.age"}, D_Age_Range, {"Age_Range"}, "D_Age_Range", JoinKind.LeftOuter),
				    #"Merged Queries1" = Table.NestedJoin(#"Merged Queries", {"demographic_distribution.gender"}, D_Gender, {"Gender"}, "D_Gender", JoinKind.LeftOuter),
				    #"Expanded D_Age_Range" = Table.ExpandTableColumn(#"Merged Queries1", "D_Age_Range", {"Age_Range_key"}, {"Age_Range_key"}),
				    #"Expanded D_Gender" = Table.ExpandTableColumn(#"Expanded D_Age_Range", "D_Gender", {"Gender_key"}, {"Gender_key"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Expanded D_Gender",{"_id", "demographic_distribution.percentage", "Age_Range_key", "Gender_key"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Removed Other Columns", {"_id"}, tmp_values, {"_id"}, "tmp_values", JoinKind.LeftOuter),
				    #"Expanded political_ads" = Table.ExpandTableColumn(#"Merged Queries2", "tmp_values", {"average_audience_size", "average_impressions", "average_spend"}, {"average_audience_size", "average_impressions", "average_spend"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded political_ads",{{"demographic_distribution.percentage", type number}}),
				    #"Inserted Multiplication" = Table.AddColumn(#"Changed Type", "Audience_dem", each [demographic_distribution.percentage] * [average_audience_size], type number),
				    #"Inserted Multiplication1" = Table.AddColumn(#"Inserted Multiplication", "Impressions_dem", each [demographic_distribution.percentage] * [average_impressions], type number),
				    #"Inserted Multiplication2" = Table.AddColumn(#"Inserted Multiplication1", "Spendings_dem", each [demographic_distribution.percentage] * [average_spend], type number),
				    #"Removed Columns" = Table.RemoveColumns(#"Inserted Multiplication2",{"average_audience_size", "average_impressions", "average_spend","demographic_distribution.percentage"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation TabularEditor_TableGroup = FACTs

