table F_Reach_Distribution
	lineageTag: 60a9a760-9a94-46a6-933f-721b154f1b28

	column _id
		dataType: string
		lineageTag: 17efc115-c7b5-41c1-9747-6544bec9121a
		summarizeBy: none
		sourceColumn: _id

		annotation SummarizationSetBy = Automatic

	column Reach
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c49b3d14-84ad-44ee-a1cd-06597c0cbe84
		summarizeBy: sum
		sourceColumn: Reach

		annotation SummarizationSetBy = Automatic

	column Age_Range_key
		dataType: string
		lineageTag: 829a8762-bc1b-450b-95d5-90984972b935
		summarizeBy: none
		sourceColumn: Age_Range_key

		annotation SummarizationSetBy = Automatic

	column Gender_key
		dataType: string
		lineageTag: e62db5f2-ed71-4b69-a299-7a6e0bf12dc7
		summarizeBy: none
		sourceColumn: Gender_key

		annotation SummarizationSetBy = Automatic

	partition F_Reach_Distribution = m
		mode: import
		queryGroup: FACTs
		source =
				let
				    Source = Odbc.DataSource("dsn=spending_db", [HierarchicalNavigation=true]),
				    spending_db_Database = Source{[Name="spending_db",Kind="Database"]}[Data],
				    v_spending_reach_breakdown_View = spending_db_Database{[Name="v_spending_reach_breakdown",Kind="View"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(v_spending_reach_breakdown_View,{ "reach_breakdown.male", "reach_breakdown.female", "reach_breakdown.age_range", "_id"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"reach_breakdown.male", "male"}, {"reach_breakdown.female", "female"}}),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Renamed Columns", {"reach_breakdown.age_range", "_id"}, "Attribute", "Reach"),
				    #"Merged Queries" = Table.NestedJoin(#"Unpivoted Columns", {"reach_breakdown.age_range"}, D_Age_Range, {"Age_Range"}, "D_Age_Range", JoinKind.LeftOuter),
				    #"Merged Queries1" = Table.NestedJoin(#"Merged Queries", {"Attribute"}, D_Gender, {"Gender"}, "D_Gender", JoinKind.LeftOuter),
				    #"Expanded D_Age_Range" = Table.ExpandTableColumn(#"Merged Queries1", "D_Age_Range", {"Age_Range_key"}, {"Age_Range_key"}),
				    #"Expanded D_Gender" = Table.ExpandTableColumn(#"Expanded D_Age_Range", "D_Gender", {"Gender_key"}, {"Gender_key"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Expanded D_Gender",{"_id", "Reach", "Age_Range_key", "Gender_key"})
				in
				    #"Removed Other Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation TabularEditor_TableGroup = FACTs

