table F_Regional_Distribution
	lineageTag: 43321dd2-13aa-48d3-ba24-c97c89f39b2c

	column Region_key
		dataType: string
		lineageTag: d7ccfeef-a30f-4312-bdb4-e24bca530797
		summarizeBy: none
		sourceColumn: Region_key

		annotation SummarizationSetBy = Automatic

	column _id
		dataType: string
		lineageTag: 7fe936c6-2f67-4e60-97d7-6f8973085429
		summarizeBy: none
		sourceColumn: _id

		annotation SummarizationSetBy = Automatic

	column Audience_reg
		dataType: double
		isHidden
		lineageTag: 77e88031-f36b-4c76-bad5-c22c85e8917a
		summarizeBy: sum
		sourceColumn: Audience_reg

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Impressions_reg
		dataType: double
		isHidden
		lineageTag: 7513faeb-7e2f-426b-9ad9-6d45069e1aab
		summarizeBy: sum
		sourceColumn: Impressions_reg

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Spendings_reg
		dataType: double
		isHidden
		lineageTag: 58fd30b8-5637-4783-b5ca-9eebeb3b855a
		summarizeBy: sum
		sourceColumn: Spendings_reg

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition F_Regional_Distribution = m
		mode: import
		queryGroup: FACTs
		source =
				let
				    Source = Odbc.DataSource("dsn=spending_db", [HierarchicalNavigation=true]),
				    spending_db_Database = Source{[Name="spending_db",Kind="Database"]}[Data],
				    v_spending_delivery_by_region_View = spending_db_Database{[Name="v_spending_delivery_by_region",Kind="View"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(v_spending_delivery_by_region_View, each ([delivery_by_region.percentage] <> null)),
				    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows", {"delivery_by_region.region"}, D_Region, {"Region"}, "D_Region", JoinKind.LeftOuter),
				    #"Expanded D_Region" = Table.ExpandTableColumn(#"Merged Queries", "D_Region", {"Region_key"}, {"Region_key"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Expanded D_Region",{"Region_key", "_id", "delivery_by_region.percentage"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Removed Other Columns", {"_id"}, tmp_values, {"_id"}, "tmp_values", JoinKind.LeftOuter),
				    #"Expanded political_ads" = Table.ExpandTableColumn(#"Merged Queries1", "tmp_values", {"average_audience_size", "average_impressions", "average_spend"}, {"average_audience_size", "average_impressions", "average_spend"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded political_ads",{{"delivery_by_region.percentage", type number}}),
				    #"Inserted Multiplication" = Table.AddColumn(#"Changed Type", "Audience_reg", each [average_audience_size] * [delivery_by_region.percentage], type number),
				    #"Inserted Multiplication1" = Table.AddColumn(#"Inserted Multiplication", "Impressions_reg", each [delivery_by_region.percentage] * [average_impressions], type number),
				    #"Inserted Multiplication2" = Table.AddColumn(#"Inserted Multiplication1", "Spendings_reg", each [delivery_by_region.percentage] * [average_spend], type number),
				    #"Removed Columns" = Table.RemoveColumns(#"Inserted Multiplication2",{"average_audience_size", "average_impressions", "average_spend","delivery_by_region.percentage"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation TabularEditor_TableGroup = FACTs

