table KPI_Metrics_Parameter
	lineageTag: 65e2eec7-a5f4-4c61-bbef-53b5d31c2a11

	measure 'Metric Selected Title' =
			SELECTCOLUMNS
			(
			    SUMMARIZE
			    (
			        KPI_Metrics_Parameter,
			        KPI_Metrics_Parameter[KPI_Metrics_Parameter],
			        KPI_Metrics_Parameter[KPI_Metrics_Parameter Fields]
			    ),
			    KPI_Metrics_Parameter[KPI_Metrics_Parameter]
			)
		displayFolder: Titles
		lineageTag: cae01089-fec2-4351-8906-f0b00c88e1f4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Selected Measure' =
			VAR __SelectedValues =
			    SELECTCOLUMNS
			    (
			        SUMMARIZE
			        (
			            KPI_Metrics_Parameter,
			            KPI_Metrics_Parameter[KPI_Metrics_Parameter],
			            KPI_Metrics_Parameter[KPI_Metrics_Parameter Fields]
			        ),
			        KPI_Metrics_Parameter[KPI_Metrics_Parameter]
			    )
			VAR SelectedValue = IF( COUNTROWS( __SelectedValues ) = 1, __SelectedValues )
			VAR vAds = [No. of Ads]
			VAR vAudience = [Audience]
			VAR vImpressions = [Impressions]
			VAR vReach = [Reach]
			VAR vSpendings = [Spendings]
			RETURN
			    SWITCH
			    (
			        SelectedValue,
			        "Ads", vAds,
			        "Audience", vAudience,
			        "Impressions", vImpressions,
			        "Reach", vReach,
			        "Spendings", vSpendings,
			        vSpendings
			    )
		lineageTag: 2beb54c0-d340-45a2-9552-6457ee0d018d

		formatStringDefinition =
				VAR _value = [Metric Selected Title] RETURN SWITCH
				(
				    TRUE( ),
				    _value = "Margin %", "0.0%",
				    "#,#0"
				)

	measure 'Metric Selected Title - Table' = [Metric Selected Title] & ": TY vs PY by Calendar Week No. and Year"
		displayFolder: Titles
		lineageTag: 4affc12d-04a0-451a-b247-8bf1697d58b7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _BlankKPI = BLANK( )
		displayFolder: Titles
		lineageTag: 6cccd7e5-83a5-4dd2-821e-13fc91d9ea49

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KPI Measure Chart Title' =
			VAR _value = [Metric Selected Title]
			VAR _metricTY =
			    SWITCH
			    (
			        TRUE( ),
			        _value = "Profit", FORMAT( [Selected Measure], "0,0#" ),
			        [Selected Measure]
			    )
			VAR _result =
			    [Metric Selected Title] & " during " & MAX( D_Calendar[Year] ) & " was " & _metricTY
			        & " and compared to the previous period was "
			        & [Selected Measure - PY Diff Format]
			RETURN
			    _result
		displayFolder: Titles
		lineageTag: 48aa893e-4fea-4536-8447-d3119b23218d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Metric Selected Title for Table Metric' = IF( [Selected Measure - PY Diff] = BLANK( ), BLANK( ), [Metric Selected Title] )
		displayFolder: Titles
		lineageTag: 9927dd57-491c-4732-90a2-4da050985841

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Selected Measure - PY Diff Format - Table Visual' =
			VAR _value = [Metric Selected Title]
			VAR up_arrow = UNICHAR( 129137 )
			VAR down_arrow = UNICHAR( 129139 )
			VAR target = [Selected Measure - PY]
			VAR targetdiffamount = [Selected Measure - PY Diff]
			VAR targetpercent = FORMAT( DIVIDE( targetdiffamount, target, 1 ), "0%" )
			VAR targetdiff =
			    SWITCH
			    (
			        TRUE( ),
			        _value = "Sales quantity", FORMAT( ROUND( targetdiffamount, 0 ), "#,0,K" ),
			        _value = "Net sales", FORMAT( ROUND( targetdiffamount, 0 ), "#,0,K" ),
			        _value = "# Orders", ROUND( targetdiffamount, 0 ),
			        _value = "ATV", ROUND( targetdiffamount, 0 ),
			        _value = "Margin %", FORMAT( DIVIDE( targetdiffamount, target, 1 ), "0%" ),
			        BLANK( )
			    )
			RETURN
			    IF
			    (
			        target = BLANK( ),
			        BLANK( ),
			        IF
			        (
			            targetdiffamount < 0,
			            targetdiff & " : " & targetpercent & " " & down_arrow,
			            targetdiff & " : " & targetpercent & " " & up_arrow
			        )
			    )
		displayFolder: _KPI
		lineageTag: 0780fed5-5659-4d2c-91c3-6db46468575a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Selected Measure - PY Diff Format' =
			VAR up_arrow = UNICHAR( 129137 )
			VAR down_arrow = UNICHAR( 129139 )
			VAR target = [Selected Measure - PY]
			VAR targetdiffamount = [Selected Measure - PY Diff]
			VAR targetpercent = FORMAT( DIVIDE( targetdiffamount, target, 0 ), "0.00%" )
			RETURN
			    IF
			    (
			        targetdiffamount = BLANK( ) || target = BLANK( ),
			        BLANK( ),
			        IF
			        (
			            targetdiffamount < 0,
			            down_arrow & " " & targetpercent,
			            up_arrow & " " & targetpercent
			        )
			    )
		displayFolder: _KPI
		lineageTag: 32543ec0-22e0-4864-9741-c255f6ff8b82

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Selected Measure - _Card Cond Format - Main Target Only' =
			SWITCH
			(
			    TRUE( ),
			    ISBLANK( [Selected Measure - PY] ), "A",
			    [Selected Measure - PY Diff] > 0, "G",
			    [Selected Measure - PY Diff] < 0, "R",
			    "A"
			)
		displayFolder: _KPI
		lineageTag: 3dc01482-82d6-463c-93e8-ee6e3f0780ca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Selected Measure - PY Diff' = [Selected Measure] - [Selected Measure - PY]
		displayFolder: _KPI
		lineageTag: b45be1df-c604-46a9-b0fa-4176ce0f9e40

		formatStringDefinition =
				VAR _value = [Metric Selected Title] RETURN SWITCH
				(
				    TRUE( ),
				    _value = "Margin %", "0.0%",
				    "#,#0"
				)

	measure 'Selected Measure - PY' = ```
			//VAR __maxDate = MAX( D_Calendar[Date] )
			//VAR __lastYear = EDATE( __maxDate, -12 )
			//RETURN
			//    CALCULATE
			//    (
			//        [Selected Measure],
			//        DATESBETWEEN
			//        (
			//            D_Calendar[Date],
			//            DATE( YEAR( __lastYear ), MONTH( __lastYear ), 1 ),
			//            __lastYear
			//        )
			//    )
			//    
			//    
			CALCULATE(
			    [Selected Measure],
			    SAMEPERIODLASTYEAR(D_Calendar[Date])
			)
			```
		displayFolder: _KPI
		lineageTag: 871425f8-23ff-451c-9528-10809f058f20

		formatStringDefinition =
				VAR _value = [Metric Selected Title] RETURN SWITCH
				(
				    TRUE( ),
				    _value = "Margin %", "0.0%",
				    "#,#0"
				)

	measure 'Selected Measure Region' = ```
			VAR __SelectedValues =
			    SELECTCOLUMNS
			    (
			        SUMMARIZE
			        (
			            KPI_Metrics_Parameter,
			            KPI_Metrics_Parameter[KPI_Metrics_Parameter],
			            KPI_Metrics_Parameter[KPI_Metrics_Parameter Fields]
			        ),
			        KPI_Metrics_Parameter[KPI_Metrics_Parameter]
			    )
			VAR SelectedValue = IF( COUNTROWS( __SelectedValues ) = 1, __SelectedValues )
			VAR vAds = [No. of Ads]
			VAR vAudience = [Audience]
			VAR vImpressions = [Impressions]
			VAR vReach = [Reach]
			VAR vSpendings = [Spendings]
			VAR result =     SWITCH
			    (
			        SelectedValue,
			        "Ads", vAds,
			        "Audience", vAudience,
			        "Impressions", vImpressions,
			        "Reach", vReach,
			        "Spendings", vSpendings,
			        BLANK( )
			    )
			VAR _region = SELECTEDVALUE(D_Region[Region_short])
			
			VAR _NumberFormat =
			    SWITCH (
			        TRUE (),
			        result <= 1E3, "#,0.",
			        result <= 1E4, "#,0,.00 K",
			        result <= 1E5, "#,0,.0 K",
			        result <= 1E6, "#,0,. K",
			        result <= 1E7, "#,0,,.00 M",
			        result <= 1E8, "#,0,,.0 M",
			        result <= 1E9, "#,0,,. M"
			    )
			RETURN
			 _region & " - " & FORMAT( ROUND( result, 0 ), _NumberFormat )  
			
			```
		lineageTag: 75b5570f-76b2-46c7-a9c8-1f754fec01ae

		formatStringDefinition =
				VAR _value = [Metric Selected Title] RETURN SWITCH
				(
				    TRUE( ),
				    _value = "Margin %", "0.0%",
				    "#,#0"
				)

	measure 'Selected Measure Top' =
			VAR __top1 = TOPN( 1, VALUES( D_Page_name[page_name] ), [Selected Measure], DESC )
			VAR __name = MAXX( __top1, D_Page_name[page_name] )
			VAR __metric = MAXX( __top1, [Selected Measure] )
			RETURN
			"Top: " & __name & " - " & FORMAT( __metric, "#,##0" )
		lineageTag: 0c600621-5adf-43b1-9e2a-6525e7c7bbe7

		formatStringDefinition =
				VAR _value = [Metric Selected Title] RETURN SWITCH
				(
				    TRUE( ),
				    _value = "Margin %", "0.0%",
				    "#,#0"
				)

	measure 'Selected Measure Gender' =
			DIVIDE(
			    [Selected Measure],
			    CALCULATE([Selected Measure],ALLSELECTED(D_Gender[Gender]))
			)
		formatString: 0.00 %
		lineageTag: 3f50eae4-f6a9-4c8d-aa72-e5c7da37120e

	measure 'Selected Measure - PY-copy' = ```
			var __maxdate = max( d_calendar[date] )
			var __lastyear = edate( __maxdate, -12 )
			return
			    calculate
			    (
			        [selected measure],
			        datesbetween
			        (
			            d_calendar[date],
			            date( year( __lastyear ), month( __lastyear ), 1 ),
			            __lastyear
			        )
			    )
			    
			    
			
			```
		displayFolder: _KPI
		lineageTag: 01c50260-be90-49f7-b074-ac005a43a629

		formatStringDefinition =
				VAR _value = [Metric Selected Title] RETURN SWITCH
				(
				    TRUE( ),
				    _value = "Margin %", "0.0%",
				    "#,#0"
				)

	column KPI_Metrics_Parameter
		lineageTag: 16581651-e679-4401-9717-7fd661f335eb
		summarizeBy: none
		sourceColumn: [Value1]
		sortByColumn: 'KPI_Metrics_Parameter Order'

		relatedColumnDetails
			groupByColumn: 'KPI_Metrics_Parameter Fields'

		annotation SummarizationSetBy = Automatic

	column 'KPI_Metrics_Parameter Fields'
		lineageTag: d9af33c5-a301-4782-a12a-f9ee295e7ae3
		summarizeBy: none
		sourceColumn: [Value2]
		sortByColumn: 'KPI_Metrics_Parameter Order'

		extendedProperty ParameterMetadata =
				{
				  "version": 3,
				  "kind": 2
				}

		annotation SummarizationSetBy = Automatic

	column 'KPI_Metrics_Parameter Order'
		formatString: 0
		lineageTag: 61058f8d-9947-4315-be96-5c38a5bbe9d2
		summarizeBy: sum
		sourceColumn: [Value3]

		annotation SummarizationSetBy = Automatic

	column KPI_image
		lineageTag: d5e783f2-161f-451c-ab0a-c523e8901c54
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: [Value4]

		annotation SummarizationSetBy = Automatic

	partition KPI_Metrics_Parameter = calculated
		mode: import
		source = ```
				{
				
				    ("Ads", NAMEOF('Calculations'[No. of Ads]), 0,"https://raw.githubusercontent.com/Thepilli/political_ads/refs/heads/main/PBI/img_ads.png"),
				    ("Audience", NAMEOF('Calculations'[Audience]), 1,"https://raw.githubusercontent.com/Thepilli/political_ads/refs/heads/main/PBI/img_audience.png"),
				    ("Impressions", NAMEOF('Calculations'[Impressions]), 2,"https://raw.githubusercontent.com/Thepilli/political_ads/refs/heads/main/PBI/img_impressions.png"),
				    ("Reach", NAMEOF('Calculations'[Reach]), 3,"https://raw.githubusercontent.com/Thepilli/political_ads/refs/heads/main/PBI/img_reach.png"),
				    ("Spendings", NAMEOF('Calculations'[Spendings]), 4,"https://raw.githubusercontent.com/Thepilli/political_ads/refs/heads/main/PBI/img_spendings.png")
				}
				
				
				
				
				
				
				```

	annotation PBI_Id = ac89d4ee95844be2a5398a87a9e95b8c

	annotation TabularEditor_TableGroup = PARAMs

